# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetsHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetsHouse
pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod ‘Alamofire’, ‘~> 5.2’
pod 'Kingfisher', '~> 5.0'
pod 'SnapKit', '~> 5.0.0'
pod 'Then'
pod 'RxDataSources', '~> 4.0'
pod 'DropDown', '2.3.2'

end
